# Generated by Django 4.2.5 on 2023-09-14 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_test_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='learning.material', verbose_name='Material of the test'),
        ),
    ]
