# Generated by Django 4.2.5 on 2023-09-15 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0004_alter_test_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500, verbose_name='Text of the answer')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Is passed')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.question', verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'user_answer',
                'verbose_name_plural': 'user_answers',
            },
        ),
        migrations.DeleteModel(
            name='Try',
        ),
    ]
