# Generated by Django 4.2.5 on 2023-09-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_useranswer_test_alter_question_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='test',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='test',
            field=models.ManyToManyField(blank=True, null=True, to='learning.test', verbose_name='Test'),
        ),
    ]
