# Generated by Django 4.2.5 on 2023-09-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_remove_useranswer_test_useranswer_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='test',
        ),
    ]
