# Generated by Django 4.2.5 on 2023-09-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_remove_useranswer_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_name',
            field=models.CharField(max_length=235, unique=True, verbose_name='Material name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=235, unique=True, verbose_name='Section name'),
        ),
    ]
